// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fgmaia/securitycodescanner/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// FileSearch is an autogenerated mock type for the FileSearch type
type FileSearch struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, path
func (_m *FileSearch) Execute(ctx context.Context, path string) <-chan domain.FileScan {
	ret := _m.Called(ctx, path)

	var r0 <-chan domain.FileScan
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan domain.FileScan); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan domain.FileScan)
		}
	}

	return r0
}
