// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fgmaia/securitycodescanner/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ScannerService is an autogenerated mock type for the ScannerService type
type ScannerService struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, path
func (_m *ScannerService) Execute(ctx context.Context, path string) (domain.ScanResult, error) {
	ret := _m.Called(ctx, path)

	var r0 domain.ScanResult
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ScanResult); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Get(0).(domain.ScanResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
